include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    no_logic_in_create_state: true
    avoid_web_libraries_in_flutter: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true

analyzer:
  exclude:
    - lib/firebase_options.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.template.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
