name: sprintinio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  collection: ^1.18.0
  uni_links: ^0.5.1
  logger: ^2.2.0
  go_router: ^13.2.3
  uuid: ^4.4.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.17.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  flutter_web_auth_2: ^3.1.2
  http: ^1.2.1
  html: ^0.15.4
  cloud_functions: ^4.7.6
  url_launcher: ^6.3.0
  
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  mockito: ^5.4.4
  fake_async: ^1.1.0
  dart_style: ^2.3.6
  test: ^1.24.9

  firebase_core_platform_interface: any
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/logo/
    - assets/emojis/
